server:
  port: 8080

  servlet:
    session:
      timeout: 5s

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://db.newlecture.com:3306/rlanddb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: rland
    password: 20231110
    
mybatis:
  Mapper-locations: mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: kr.co.rland.app.entity

logging:
  level:
    kr:
      co:
        rland:
          app:
            repository: DEBUG
            #  FATAL/ERORR/WARN/INFO/DEBUG/TRACE/ALL
