spring:

  profiles:
    active: dev
    # active:dev => dev.yml사용

  # datasource:
  #   driver-class-name: org.mariadb.jdbc.Driver
  #   url: jdbc:mariadb://db.newlecture.com:3306/rlanddb?serverTimezone=Asia/Seoul&amp;characterEncoding=UTF-8
  #   username: rland
  #   password: 20231110
